
PROGRAM _INIT
	(* Insert code here *)
END_PROGRAM

PROGRAM _CYCLIC
	(* Insert code here *)
	// do wyjebania tension enable
	actStopped;
	actStopping;
	actAborting;
	actAborted;
	actClearing;
	actProdResetting;
	actProdIdle;
	actProdStarting;
	actProdExecute;
	actProdCompleting;
	actProdComplete;
	actManResetting;
	actManIdle;
	
	 
END_PROGRAM

PROGRAM _EXIT
	(* Insert code here *)
	 
END_PROGRAM

